# Generated by Django 4.1.6 on 2023-02-02 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dob', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_count', models.IntegerField(default=0)),
            ],
        ),
    ]
